apiVersion: v1
kind: Service
metadata:
  name: be-service
spec:
  selector:
    app: my-site-be
  type: LoadBalancer 
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
      nodePort: 31000